name: Ruby

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: root
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    container:
      image: ruby:2.6.5
      env:
        RAILS_ENV: test
        RAILS_DATABASE_HOST: mysql # this is needed
        MYSQL_ROOT_PASSWORD: password
        MYSQL_DATABASE: root
      steps:
      - uses: actions/checkout@v1
      - name: Prepare bundler
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3
      - name: Prepare database
        run: |
          rails db:create
          rails db:migrade
      - name: Run test
        run: |
          rubocop
          rspec